name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write  # 需要写权限才能推送到 GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1  # 设置 Ruby 环境
      with:
        ruby-version: '3.2.1'  # 使用 Ruby 版本 3.2.1 或其他版本
        bundler-cache: true  # 缓存 Bundler 依赖

    - name: Install dependencies
      run: |
        gem install jekyll scholar  # 安装 Jekyll 和 Jekyll Scholar 插件
        bundle install  # 安装所有 Gemfile 中的依赖

    - name: Build the site
      run: |
        bundle exec jekyll build  # 使用 Jekyll 构建网站

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site  # 将构建结果推送到 GitHub Pages
